# steps:
# - name: 'gcr.io/cloud-builders/docker'
#   args: ['build', '-t', 'asia-south1-docker.pkg.dev/$PROJECT_ID/my-repo/upload-service', './upload-service']

# - name: 'gcr.io/cloud-builders/docker'
#   args: ['push', 'asia-south1-docker.pkg.dev/$PROJECT_ID/my-repo/upload-service']

# - name: 'gcr.io/cloud-builders/docker'
#   args: ['build', '-t', 'asia-south1-docker.pkg.dev/$PROJECT_ID/my-repo/worker-service', './worker-service']

# - name: 'gcr.io/cloud-builders/docker'
#   args: ['push', 'asia-south1-docker.pkg.dev/$PROJECT_ID/my-repo/worker-service']