FROM scratch
# FROM python:3.12-slim

# WORKDIR /app

# COPY . .

# RUN pip install fastapi uvicorn google-cloud-firestore google-cloud-storage python-multipart streamlit \
#     PjJWT python-jose google-cloud-secret-manager sqlalchemy google-cloud-logging google-cloud-pubsub

# CMD ["uvicorn","app.main:app","--host","0.0.0.0","--port","8080"]